# Interop Test Platofrm CircleCI

version: 2
jobs:
  build:
    machine: true # Use a Linux VM instead of docker environment
    working_directory: ~/repo # Default working directory, where your project will be clo

    steps:
      - checkout

      - run: 
        name: Generate configuration files
        command: make init

      - run: 
        name: Run docker containers
        command: make run

      - run: 
        name: Install Componser and Node dependecies
        command: make install

      - run: 
          name: Check installation
          command: |
            FILE=/runtime/installed
            if test -f "$FILE"; then
                echo "Installation succesful"
            else 
                echo "Installation fail"
            fi
