# Interop Test Platofrm CircleCI

version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01 # Define a machine who has support for docker compose 3.7
    working_directory: ~/repo # Default working directory, where your project will be clo

    steps:
      - checkout

      - run: 
          name: Generate configuration files
          command: make init

      - run: 
          name: Run docker containers
          command: make run

      - run: 
          name: Install Componser and Node dependecies
          command: make install

      - run: 
          name: Check installation
          command: |
            FILE=./runtime/installed
            if test -f "$FILE"; then
                echo "Installation succesful"
            else 
                echo "Installation fail"
                exit 2
            fi
            
      - run:
          name: Run Tests
          command: make test
      
      - store_test_results:
          path: test-results

      - store_artifacts:
          path: tests/Browser/screenshots
