openapi: 3.0.0
info:
  version: "1.0"
  title: SP API
paths:
  '{X-Callback-URL}':
    put:
      summary: Callback URL
      description: The client endpoint is identified from the X-Callback-URL supplied in the POST request header.
